'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.2407.
'
Namespace CIMA_AD
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Service1Soap", [Namespace]:="http://tempuri.org/CIMA_Servicios/Service1")>  _
    Public Class Service1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.8.50.213/CIMA_Servicios/Service1.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CIMA_Servicios/Service1/IsAuthenticated", RequestNamespace:="http://tempuri.org/CIMA_Servicios/Service1", ResponseNamespace:="http://tempuri.org/CIMA_Servicios/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsAuthenticated(ByVal domain As String, ByVal username As String, ByVal pwd As String) As Boolean
            Dim results() As Object = Me.Invoke("IsAuthenticated", New Object() {domain, username, pwd})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginIsAuthenticated(ByVal domain As String, ByVal username As String, ByVal pwd As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("IsAuthenticated", New Object() {domain, username, pwd}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndIsAuthenticated(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CIMA_Servicios/Service1/ChangePassword", RequestNamespace:="http://tempuri.org/CIMA_Servicios/Service1", ResponseNamespace:="http://tempuri.org/CIMA_Servicios/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ChangePassword(ByVal domain As String, ByVal username As String, ByVal pwd_old As String, ByVal pwd_new As String) As Boolean
            Dim results() As Object = Me.Invoke("ChangePassword", New Object() {domain, username, pwd_old, pwd_new})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginChangePassword(ByVal domain As String, ByVal username As String, ByVal pwd_old As String, ByVal pwd_new As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ChangePassword", New Object() {domain, username, pwd_old, pwd_new}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndChangePassword(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
    End Class
End Namespace
