'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.2407.
'
Namespace CIMAServeiIntegracio
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WSEInteroperability", [Namespace]:="http://tempuri.org/")>  _
    Public Class ServeiIntegracio
        Inherits Microsoft.Web.Services2.WebServicesClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://timor.cetir.org/CIMAServeiIntegracio/ServeiIntegracio.svc/WSE"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/BegginTransaction", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BegginTransaction() As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> Transaccio
            Dim results() As Object = Me.Invoke("BegginTransaction", New Object(-1) {})
            Return CType(results(0),Transaccio)
        End Function
        
        '<remarks/>
        Public Function BeginBegginTransaction(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("BegginTransaction", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndBegginTransaction(ByVal asyncResult As System.IAsyncResult) As Transaccio
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Transaccio)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/RollbackTransaction", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RollbackTransaction(ByVal ID_Transaccio As System.Guid, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_TransaccioSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> Transaccio
            Dim results() As Object = Me.Invoke("RollbackTransaction", New Object() {ID_Transaccio, ID_TransaccioSpecified})
            Return CType(results(0),Transaccio)
        End Function
        
        '<remarks/>
        Public Function BeginRollbackTransaction(ByVal ID_Transaccio As System.Guid, ByVal ID_TransaccioSpecified As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RollbackTransaction", New Object() {ID_Transaccio, ID_TransaccioSpecified}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRollbackTransaction(ByVal asyncResult As System.IAsyncResult) As Transaccio
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Transaccio)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/CommitTransaccio", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CommitTransaccio(ByVal ID_Transaccio As System.Guid, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_TransaccioSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> Transaccio
            Dim results() As Object = Me.Invoke("CommitTransaccio", New Object() {ID_Transaccio, ID_TransaccioSpecified})
            Return CType(results(0),Transaccio)
        End Function
        
        '<remarks/>
        Public Function BeginCommitTransaccio(ByVal ID_Transaccio As System.Guid, ByVal ID_TransaccioSpecified As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CommitTransaccio", New Object() {ID_Transaccio, ID_TransaccioSpecified}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndCommitTransaccio(ByVal asyncResult As System.IAsyncResult) As Transaccio
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Transaccio)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/GetHoresLliures", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetHoresLliures( _
                    ByVal ID_Transaccio As System.Guid,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_TransaccioSpecified As Boolean,  _
                    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Institucio_Pagament As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Prova As String,  _
                    ByVal Desde As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal DesdeSpecified As Boolean,  _
                    ByVal Fins As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal FinsSpecified As Boolean,  _
                    ByVal Maxim_Hores As Integer,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal Maxim_HoresSpecified As Boolean,  _
                    ByVal Franja_Horaria As FranjaHoraria,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal Franja_HorariaSpecified As Boolean,  _
                    ByVal Hora_inici As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal Hora_iniciSpecified As Boolean,  _
                    ByVal Hora_Fi As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal Hora_FiSpecified As Boolean,  _
                    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Centre As String,  _
                    ByVal Urgent As Boolean,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal UrgentSpecified As Boolean,  _
                    ByVal Especial As Boolean,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal EspecialSpecified As Boolean,  _
                    ByVal Anestesia As Boolean,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal AnestesiaSpecified As Boolean,  _
                    ByVal Ambulancia As Boolean,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal AmbulanciaSpecified As Boolean,  _
                    <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Cgm.Integracions.CIMA.Business")> ByVal Mantenir_Hores_Reservades() As HoraReservada) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Cgm.Integracions.CIMA.Business")> HoraReservada()
            Dim results() As Object = Me.Invoke("GetHoresLliures", New Object() {ID_Transaccio, ID_TransaccioSpecified, ID_Institucio_Pagament, ID_Prova, Desde, DesdeSpecified, Fins, FinsSpecified, Maxim_Hores, Maxim_HoresSpecified, Franja_Horaria, Franja_HorariaSpecified, Hora_inici, Hora_iniciSpecified, Hora_Fi, Hora_FiSpecified, ID_Centre, Urgent, UrgentSpecified, Especial, EspecialSpecified, Anestesia, AnestesiaSpecified, Ambulancia, AmbulanciaSpecified, Mantenir_Hores_Reservades})
            Return CType(results(0),HoraReservada())
        End Function
        
        '<remarks/>
        Public Function BeginGetHoresLliures( _
                    ByVal ID_Transaccio As System.Guid,  _
                    ByVal ID_TransaccioSpecified As Boolean,  _
                    ByVal ID_Institucio_Pagament As String,  _
                    ByVal ID_Prova As String,  _
                    ByVal Desde As Date,  _
                    ByVal DesdeSpecified As Boolean,  _
                    ByVal Fins As Date,  _
                    ByVal FinsSpecified As Boolean,  _
                    ByVal Maxim_Hores As Integer,  _
                    ByVal Maxim_HoresSpecified As Boolean,  _
                    ByVal Franja_Horaria As FranjaHoraria,  _
                    ByVal Franja_HorariaSpecified As Boolean,  _
                    ByVal Hora_inici As Date,  _
                    ByVal Hora_iniciSpecified As Boolean,  _
                    ByVal Hora_Fi As Date,  _
                    ByVal Hora_FiSpecified As Boolean,  _
                    ByVal ID_Centre As String,  _
                    ByVal Urgent As Boolean,  _
                    ByVal UrgentSpecified As Boolean,  _
                    ByVal Especial As Boolean,  _
                    ByVal EspecialSpecified As Boolean,  _
                    ByVal Anestesia As Boolean,  _
                    ByVal AnestesiaSpecified As Boolean,  _
                    ByVal Ambulancia As Boolean,  _
                    ByVal AmbulanciaSpecified As Boolean,  _
                    ByVal Mantenir_Hores_Reservades() As HoraReservada,  _
                    ByVal callback As System.AsyncCallback,  _
                    ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetHoresLliures", New Object() {ID_Transaccio, ID_TransaccioSpecified, ID_Institucio_Pagament, ID_Prova, Desde, DesdeSpecified, Fins, FinsSpecified, Maxim_Hores, Maxim_HoresSpecified, Franja_Horaria, Franja_HorariaSpecified, Hora_inici, Hora_iniciSpecified, Hora_Fi, Hora_FiSpecified, ID_Centre, Urgent, UrgentSpecified, Especial, EspecialSpecified, Anestesia, AnestesiaSpecified, Ambulancia, AmbulanciaSpecified, Mantenir_Hores_Reservades}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetHoresLliures(ByVal asyncResult As System.IAsyncResult) As HoraReservada()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),HoraReservada())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/ConfirmarHoraPacient", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConfirmarHoraPacient(ByVal ID_Transaccio As System.Guid, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_TransaccioSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Dades_Pacient As Pacient, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Hora_Reservada As HoraReservada) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> Cita
            Dim results() As Object = Me.Invoke("ConfirmarHoraPacient", New Object() {ID_Transaccio, ID_TransaccioSpecified, Dades_Pacient, Hora_Reservada})
            Return CType(results(0),Cita)
        End Function
        
        '<remarks/>
        Public Function BeginConfirmarHoraPacient(ByVal ID_Transaccio As System.Guid, ByVal ID_TransaccioSpecified As Boolean, ByVal Dades_Pacient As Pacient, ByVal Hora_Reservada As HoraReservada, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ConfirmarHoraPacient", New Object() {ID_Transaccio, ID_TransaccioSpecified, Dades_Pacient, Hora_Reservada}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndConfirmarHoraPacient(ByVal asyncResult As System.IAsyncResult) As Cita
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Cita)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/ForzarHoraPacient", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ForzarHoraPacient( _
                    ByVal ID_Transaccio As System.Guid,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_TransaccioSpecified As Boolean,  _
                    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Dades_Pacient As Pacient,  _
                    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Institucio_Pagament As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Prova As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Centre As String,  _
                    ByVal Data_Inici_Realitzacio As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal Data_Inici_RealitzacioSpecified As Boolean,  _
                    ByVal Data_Final_Realitzacio As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal Data_Final_RealitzacioSpecified As Boolean,  _
                    ByVal Urgent As Boolean,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal UrgentSpecified As Boolean,  _
                    ByVal Anestesia As Boolean,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal AnestesiaSpecified As Boolean,  _
                    ByVal Ambulancia As Boolean,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal AmbulanciaSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> Cita
            Dim results() As Object = Me.Invoke("ForzarHoraPacient", New Object() {ID_Transaccio, ID_TransaccioSpecified, Dades_Pacient, ID_Institucio_Pagament, ID_Prova, ID_Centre, Data_Inici_Realitzacio, Data_Inici_RealitzacioSpecified, Data_Final_Realitzacio, Data_Final_RealitzacioSpecified, Urgent, UrgentSpecified, Anestesia, AnestesiaSpecified, Ambulancia, AmbulanciaSpecified})
            Return CType(results(0),Cita)
        End Function
        
        '<remarks/>
        Public Function BeginForzarHoraPacient( _
                    ByVal ID_Transaccio As System.Guid,  _
                    ByVal ID_TransaccioSpecified As Boolean,  _
                    ByVal Dades_Pacient As Pacient,  _
                    ByVal ID_Institucio_Pagament As String,  _
                    ByVal ID_Prova As String,  _
                    ByVal ID_Centre As String,  _
                    ByVal Data_Inici_Realitzacio As Date,  _
                    ByVal Data_Inici_RealitzacioSpecified As Boolean,  _
                    ByVal Data_Final_Realitzacio As Date,  _
                    ByVal Data_Final_RealitzacioSpecified As Boolean,  _
                    ByVal Urgent As Boolean,  _
                    ByVal UrgentSpecified As Boolean,  _
                    ByVal Anestesia As Boolean,  _
                    ByVal AnestesiaSpecified As Boolean,  _
                    ByVal Ambulancia As Boolean,  _
                    ByVal AmbulanciaSpecified As Boolean,  _
                    ByVal callback As System.AsyncCallback,  _
                    ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ForzarHoraPacient", New Object() {ID_Transaccio, ID_TransaccioSpecified, Dades_Pacient, ID_Institucio_Pagament, ID_Prova, ID_Centre, Data_Inici_Realitzacio, Data_Inici_RealitzacioSpecified, Data_Final_Realitzacio, Data_Final_RealitzacioSpecified, Urgent, UrgentSpecified, Anestesia, AnestesiaSpecified, Ambulancia, AmbulanciaSpecified}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndForzarHoraPacient(ByVal asyncResult As System.IAsyncResult) As Cita
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Cita)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/AssociarCitaCGMEpisodiExtern", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AssociarCitaCGMEpisodiExtern(ByVal ID_Transaccio As System.Guid, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_TransaccioSpecified As Boolean, ByVal ID_Cita_CGM As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_Cita_CGMSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Episodi As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> Cita
            Dim results() As Object = Me.Invoke("AssociarCitaCGMEpisodiExtern", New Object() {ID_Transaccio, ID_TransaccioSpecified, ID_Cita_CGM, ID_Cita_CGMSpecified, ID_Episodi})
            Return CType(results(0),Cita)
        End Function
        
        '<remarks/>
        Public Function BeginAssociarCitaCGMEpisodiExtern(ByVal ID_Transaccio As System.Guid, ByVal ID_TransaccioSpecified As Boolean, ByVal ID_Cita_CGM As Integer, ByVal ID_Cita_CGMSpecified As Boolean, ByVal ID_Episodi As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AssociarCitaCGMEpisodiExtern", New Object() {ID_Transaccio, ID_TransaccioSpecified, ID_Cita_CGM, ID_Cita_CGMSpecified, ID_Episodi}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAssociarCitaCGMEpisodiExtern(ByVal asyncResult As System.IAsyncResult) As Cita
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Cita)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/RecepcioDePacient", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RecepcioDePacient(ByVal ID_Transaccio As System.Guid, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_TransaccioSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Dades_Pacient As Pacient, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Episodi As String, ByVal ID_Cita_CGM As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_Cita_CGMSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Prova As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Centre As String, ByVal Data_Realitzacio As Date, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal Data_RealitzacioSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Orientacio_diagnostica As String) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable:=false)> Integer()
            Dim results() As Object = Me.Invoke("RecepcioDePacient", New Object() {ID_Transaccio, ID_TransaccioSpecified, Dades_Pacient, ID_Episodi, ID_Cita_CGM, ID_Cita_CGMSpecified, ID_Prova, ID_Centre, Data_Realitzacio, Data_RealitzacioSpecified, Orientacio_diagnostica})
            Return CType(results(0),Integer())
        End Function
        
        '<remarks/>
        Public Function BeginRecepcioDePacient(ByVal ID_Transaccio As System.Guid, ByVal ID_TransaccioSpecified As Boolean, ByVal Dades_Pacient As Pacient, ByVal ID_Episodi As String, ByVal ID_Cita_CGM As Integer, ByVal ID_Cita_CGMSpecified As Boolean, ByVal ID_Prova As String, ByVal ID_Centre As String, ByVal Data_Realitzacio As Date, ByVal Data_RealitzacioSpecified As Boolean, ByVal Orientacio_diagnostica As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RecepcioDePacient", New Object() {ID_Transaccio, ID_TransaccioSpecified, Dades_Pacient, ID_Episodi, ID_Cita_CGM, ID_Cita_CGMSpecified, ID_Prova, ID_Centre, Data_Realitzacio, Data_RealitzacioSpecified, Orientacio_diagnostica}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRecepcioDePacient(ByVal asyncResult As System.IAsyncResult) As Integer()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/AnularDadesEpisodi", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub AnularDadesEpisodi(ByVal ID_Transaccio As System.Guid, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_TransaccioSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Pacient_Extern As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Episodi As String, ByVal ID_Cita_CGM As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_Cita_CGMSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Motiu_Anulacio As String)
            Me.Invoke("AnularDadesEpisodi", New Object() {ID_Transaccio, ID_TransaccioSpecified, ID_Pacient_Extern, ID_Episodi, ID_Cita_CGM, ID_Cita_CGMSpecified, Motiu_Anulacio})
        End Sub
        
        '<remarks/>
        Public Function BeginAnularDadesEpisodi(ByVal ID_Transaccio As System.Guid, ByVal ID_TransaccioSpecified As Boolean, ByVal ID_Pacient_Extern As String, ByVal ID_Episodi As String, ByVal ID_Cita_CGM As Integer, ByVal ID_Cita_CGMSpecified As Boolean, ByVal Motiu_Anulacio As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AnularDadesEpisodi", New Object() {ID_Transaccio, ID_TransaccioSpecified, ID_Pacient_Extern, ID_Episodi, ID_Cita_CGM, ID_Cita_CGMSpecified, Motiu_Anulacio}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Sub EndAnularDadesEpisodi(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/CanviDadesRecepcioDePacient", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CanviDadesRecepcioDePacient(ByVal ID_Transaccio As System.Guid, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_TransaccioSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Pacient_Extern As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Episodi As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Nova_Prova As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Orientacio_diagnostica As String) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable:=false)> Integer()
            Dim results() As Object = Me.Invoke("CanviDadesRecepcioDePacient", New Object() {ID_Transaccio, ID_TransaccioSpecified, ID_Pacient_Extern, ID_Episodi, ID_Nova_Prova, Orientacio_diagnostica})
            Return CType(results(0),Integer())
        End Function
        
        '<remarks/>
        Public Function BeginCanviDadesRecepcioDePacient(ByVal ID_Transaccio As System.Guid, ByVal ID_TransaccioSpecified As Boolean, ByVal ID_Pacient_Extern As String, ByVal ID_Episodi As String, ByVal ID_Nova_Prova As String, ByVal Orientacio_diagnostica As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CanviDadesRecepcioDePacient", New Object() {ID_Transaccio, ID_TransaccioSpecified, ID_Pacient_Extern, ID_Episodi, ID_Nova_Prova, Orientacio_diagnostica}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndCanviDadesRecepcioDePacient(ByVal asyncResult As System.IAsyncResult) As Integer()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/RecitarPacient", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RecitarPacient( _
                    ByVal ID_Transaccio As System.Guid,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_TransaccioSpecified As Boolean,  _
                    ByVal ID_Cita_CGM As Integer,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_Cita_CGMSpecified As Boolean,  _
                    ByVal Desde As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal DesdeSpecified As Boolean,  _
                    ByVal Fins As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal FinsSpecified As Boolean,  _
                    ByVal Maxim_Hores As Integer,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal Maxim_HoresSpecified As Boolean,  _
                    ByVal Franja_Horaria As FranjaHoraria,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal Franja_HorariaSpecified As Boolean,  _
                    ByVal Hora_inici As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal Hora_iniciSpecified As Boolean,  _
                    ByVal Hora_Fi As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal Hora_FiSpecified As Boolean) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Cgm.Integracions.CIMA.Business")> HoraReservada()
            Dim results() As Object = Me.Invoke("RecitarPacient", New Object() {ID_Transaccio, ID_TransaccioSpecified, ID_Cita_CGM, ID_Cita_CGMSpecified, Desde, DesdeSpecified, Fins, FinsSpecified, Maxim_Hores, Maxim_HoresSpecified, Franja_Horaria, Franja_HorariaSpecified, Hora_inici, Hora_iniciSpecified, Hora_Fi, Hora_FiSpecified})
            Return CType(results(0),HoraReservada())
        End Function
        
        '<remarks/>
        Public Function BeginRecitarPacient( _
                    ByVal ID_Transaccio As System.Guid,  _
                    ByVal ID_TransaccioSpecified As Boolean,  _
                    ByVal ID_Cita_CGM As Integer,  _
                    ByVal ID_Cita_CGMSpecified As Boolean,  _
                    ByVal Desde As Date,  _
                    ByVal DesdeSpecified As Boolean,  _
                    ByVal Fins As Date,  _
                    ByVal FinsSpecified As Boolean,  _
                    ByVal Maxim_Hores As Integer,  _
                    ByVal Maxim_HoresSpecified As Boolean,  _
                    ByVal Franja_Horaria As FranjaHoraria,  _
                    ByVal Franja_HorariaSpecified As Boolean,  _
                    ByVal Hora_inici As Date,  _
                    ByVal Hora_iniciSpecified As Boolean,  _
                    ByVal Hora_Fi As Date,  _
                    ByVal Hora_FiSpecified As Boolean,  _
                    ByVal callback As System.AsyncCallback,  _
                    ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RecitarPacient", New Object() {ID_Transaccio, ID_TransaccioSpecified, ID_Cita_CGM, ID_Cita_CGMSpecified, Desde, DesdeSpecified, Fins, FinsSpecified, Maxim_Hores, Maxim_HoresSpecified, Franja_Horaria, Franja_HorariaSpecified, Hora_inici, Hora_iniciSpecified, Hora_Fi, Hora_FiSpecified}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRecitarPacient(ByVal asyncResult As System.IAsyncResult) As HoraReservada()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),HoraReservada())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/ConfirmarHoraRecitadaPacient", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConfirmarHoraRecitadaPacient(ByVal ID_Transaccio As System.Guid, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_TransaccioSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Hora_Reservada As HoraReservada) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> Cita
            Dim results() As Object = Me.Invoke("ConfirmarHoraRecitadaPacient", New Object() {ID_Transaccio, ID_TransaccioSpecified, Hora_Reservada})
            Return CType(results(0),Cita)
        End Function
        
        '<remarks/>
        Public Function BeginConfirmarHoraRecitadaPacient(ByVal ID_Transaccio As System.Guid, ByVal ID_TransaccioSpecified As Boolean, ByVal Hora_Reservada As HoraReservada, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ConfirmarHoraRecitadaPacient", New Object() {ID_Transaccio, ID_TransaccioSpecified, Hora_Reservada}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndConfirmarHoraRecitadaPacient(ByVal asyncResult As System.IAsyncResult) As Cita
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Cita)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/GetIDEpisodiCGM", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub GetIDEpisodiCGM(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Pacient_Extern As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ID_Episodi_Extern As String, ByRef GetIDEpisodiCGMResult As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef GetIDEpisodiCGMResultSpecified As Boolean)
            Dim results() As Object = Me.Invoke("GetIDEpisodiCGM", New Object() {ID_Pacient_Extern, ID_Episodi_Extern})
            GetIDEpisodiCGMResult = CType(results(0),Integer)
            GetIDEpisodiCGMResultSpecified = CType(results(1),Boolean)
        End Sub
        
        '<remarks/>
        Public Function BeginGetIDEpisodiCGM(ByVal ID_Pacient_Extern As String, ByVal ID_Episodi_Extern As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetIDEpisodiCGM", New Object() {ID_Pacient_Extern, ID_Episodi_Extern}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Sub EndGetIDEpisodiCGM(ByVal asyncResult As System.IAsyncResult, ByRef GetIDEpisodiCGMResult As Integer, ByRef GetIDEpisodiCGMResultSpecified As Boolean)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            GetIDEpisodiCGMResult = CType(results(0),Integer)
            GetIDEpisodiCGMResultSpecified = CType(results(1),Boolean)
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServeiIntegracio/GetDICOMEstudisUID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDICOMEstudisUID(ByVal ID_Episodi_CGM As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ID_Episodi_CGMSpecified As Boolean) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")> String()
            Dim results() As Object = Me.Invoke("GetDICOMEstudisUID", New Object() {ID_Episodi_CGM, ID_Episodi_CGMSpecified})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGetDICOMEstudisUID(ByVal ID_Episodi_CGM As Integer, ByVal ID_Episodi_CGMSpecified As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetDICOMEstudisUID", New Object() {ID_Episodi_CGM, ID_Episodi_CGMSpecified}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetDICOMEstudisUID(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Cgm.Integracions.CIMA.Business")>  _
    Public Class Transaccio
        
        '<remarks/>
        Public Data_Cancelacio As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Data_CancelacioSpecified As Boolean
        
        '<remarks/>
        Public Data_Confirmacio As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Data_ConfirmacioSpecified As Boolean
        
        '<remarks/>
        Public Data_Creacio As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Data_CreacioSpecified As Boolean
        
        '<remarks/>
        Public Data_Ultima_Actualitzacio As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Data_Ultima_ActualitzacioSpecified As Boolean
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Estat_Transaccio As String
        
        '<remarks/>
        Public ID As System.Guid
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public IDSpecified As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Cgm.Integracions.CIMA.Business")>  _
    Public Class Cita
        
        '<remarks/>
        Public Data_Creacio As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Data_CreacioSpecified As Boolean
        
        '<remarks/>
        Public Data_Realitzacio As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Data_RealitzacioSpecified As Boolean
        
        '<remarks/>
        Public ID_CGM As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ID_CGMSpecified As Boolean
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public ID_Centre As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public ID_Episodi_Extern As String
        
        '<remarks/>
        Public ID_Estat As Char
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ID_EstatSpecified As Boolean
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public ID_Institucio_Pagament As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public ID_Pacient_Extern As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public ID_Prova As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Orientacio_Diagnostica As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Cgm.Integracions.CIMA.Business")>  _
    Public Class Pacient
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Adreca As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public CIP As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Codi_Postal As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Cognom1 As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Cognom2 As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DNI As String
        
        '<remarks/>
        Public Data_Naixament As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Data_NaixamentSpecified As Boolean
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public E_Mail As String
        
        '<remarks/>
        Public ID_CGM As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ID_CGMSpecified As Boolean
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public ID_Pacient_Extern As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Mobil As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Nom As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Poblacio As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Poblacio_Naixament As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Professio As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Sexe As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Telefon As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Cgm.Integracions.CIMA.Business")>  _
    Public Class HoraReservada
        
        '<remarks/>
        Public DataHoraReservada As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public DataHoraReservadaSpecified As Boolean
        
        '<remarks/>
        Public Durada As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public DuradaSpecified As Boolean
        
        '<remarks/>
        Public Grup As Short
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public GrupSpecified As Boolean
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public ID_Centre As String
        
        '<remarks/>
        Public ID_Cita As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ID_CitaSpecified As Boolean
        
        '<remarks/>
        Public ID_Interval_Inici As Byte
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ID_Interval_IniciSpecified As Boolean
        
        '<remarks/>
        Public ID_Linia As Byte
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ID_LiniaSpecified As Boolean
        
        '<remarks/>
        Public ID_Tram As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ID_TramSpecified As Boolean
        
        '<remarks/>
        Public N_Intervals As Byte
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public N_IntervalsSpecified As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/CGM.Services.Integracio")>  _
    Public Enum FranjaHoraria
        
        '<remarks/>
        QUALSEVOL
        
        '<remarks/>
        MATI
        
        '<remarks/>
        MIGDIA
        
        '<remarks/>
        TARDA
        
        '<remarks/>
        NIT
    End Enum
End Namespace
